server:
  port: 9003
spring:
  application:
    name: crazychat-group
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123
    url: jdbc:mysql://192.168.117.128:3306/crazychat_group?characterEncoding=utf-8
  jpa:
    database: mysql
    show-sql: true
  data:
    mongodb:
      host: 192.168.117.128
      database: groupDB

# eureka配置
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:4170/eureka/
  instance:
    prefer-ip-address: true     # 跨域访问
