server:
  port: 9002
spring:
  application:
    name: crazychat-user
  datasource:   # 配置数据源
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.117.128:3306/crazychat_user?characterEncoding=utf-8
    username: root
    password: 123
  jpa:    # 配置jpa
    show-sql: true
    database: mysql
  # 发送邮件
  mail:
    username: 2789519045@qq.com
    password: dfsmismiilkydghh    # 邮箱授权码   dfsmismiilkydghh
    host: smtp.qq.com
    properties:
      mail:
        smtp:
          ssl:
            enable: true     # 开启ssl安全连接
  # redis配置
  redis:
    database: 0
    host: 192.168.117.128
    port: 6379
jwt:
  config:
    # 加盐
    key: ericjin
    ttl: 3600000

# eureka配置
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:4170/eureka/
  instance:
    prefer-ip-address: true     # 跨域访问
