server:
  port: 9001

spring:
  application:
    name: crazychat-chat
  data:
    mongodb:
      host: 192.168.117.128
      database: chatDB

# eureka配置
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:4170/eureka/
  instance:
    prefer-ip-address: true     # 跨域访问

    